### ISSUE TITLE
fail2ban 0.10.5

### ISSUE THREAD

**Issue by antonzhelyazkov** [zevilz/NagiosFail2banStatus#1]
OS Centos 7
Version fail2ban-0.10.5-2.el7

Hi,

It seems that new version of fail2ban have differences in process tree. Currently ```F2B_CHECK_PROCCESS=`ps -e | grep fail2ban-server``` have empty value so script exit s with ```ERROR! Fail2ban not running.``` . 
Could create new version with fix of this issue?

**Comment by zevilz** [comment]
Thanks for feedback. Fixed.
